platform :ios, '8.0'

target "OCStartup" do
    
pod 'SDWebImage', '~> 4.0.0'
pod 'Masonry', '~> 1.0.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'TPKeyboardAvoiding', '~> 1.3.1'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'Realm', '~> 2.4.2'

end